import type {
  MultipleChoiceContent,
  MultipleSelectContent,
  QuestionType,
  ArtifactPbqContent,
  RemediationSelectContent,
  FillInContent,
  PbqArtifact,
  PbqSubQuestion,
} from '@/db/question-types';
import { randomOrder, applyOrder } from './option-order';

// Client-safe views of question content — the correct answer, the overall
// explanation, and per-distractor explanations are never included. This is
// the only shape a Server Component may pass into a Client Component for an
// unanswered card: if a field isn't on these types, it physically cannot
// reach the browser before submitAnswer() runs.
//
// `optionOrder` is the one exception worth calling out: it IS sent
// pre-submit, because it's generated by a random shuffle independent of
// which option is correct (see src/lib/option-order.ts) — it carries no
// correctness signal on its own. It's the display permutation
// (`options` here is already reordered by it); the client echoes it back to
// submitAnswer so grading can translate the displayed selection back to
// stored order without ever sending `correct` to the browser.

export interface PublicMultipleChoiceContent {
  question: string;
  options: string[];
  optionOrder: number[];
}

export interface PublicMultipleSelectContent {
  question: string;
  options: string[];
  requiredCount: number;
  optionOrder: number[];
}

// The artifact itself (log lines / table rows) is safe to send as-is — it
// doesn't reveal which rows/lines are correct on its own.

export type PublicPbqSubQuestion =
  | { answerMode: 'options'; question: string; options: string[]; requiredCount?: number }
  | { answerMode: 'artifact_rows'; question: string; requiredCount?: number }
  | { answerMode: 'cell_value'; question: string; column: string; rows: number[]; options: string[] };

export interface PublicArtifactPbqContent {
  scenario?: string;
  artifact: PbqArtifact;
  subQuestions: PublicPbqSubQuestion[];
}

export interface PublicRemediationSelectContent {
  scenario: string;
  question: string;
  actions: string[];
}

export interface PublicFillInContent {
  question: string;
}

export type PublicQuestionContent =
  | PublicMultipleChoiceContent
  | PublicMultipleSelectContent
  | PublicArtifactPbqContent
  | PublicRemediationSelectContent
  | PublicFillInContent;

export type PublicCardType =
  | 'multiple_choice'
  | 'multiple_select'
  | 'log_analysis'
  | 'config_table'
  | 'remediation_select'
  | 'fill_in';

export interface PublicCard {
  id: string;
  domain: string;
  topic: string;
  type: PublicCardType;
  content: PublicQuestionContent;
}

function toPublicSubQuestion(sq: PbqSubQuestion): PublicPbqSubQuestion {
  if (sq.answerMode === 'options') {
    return { answerMode: 'options', question: sq.question, options: sq.options, requiredCount: sq.requiredCount };
  }
  if (sq.answerMode === 'artifact_rows') {
    return { answerMode: 'artifact_rows', question: sq.question, requiredCount: sq.requiredCount };
  }
  return { answerMode: 'cell_value', question: sq.question, column: sq.column, rows: sq.rows, options: sq.options };
}

export function toPublicContent(
  type: QuestionType,
  content:
    | MultipleChoiceContent
    | MultipleSelectContent
    | ArtifactPbqContent
    | RemediationSelectContent
    | FillInContent
): PublicQuestionContent {
  if (type === 'fill_in') {
    const c = content as FillInContent;
    return { question: c.question };
  }
  if (type === 'multiple_select') {
    const c = content as MultipleSelectContent;
    const optionOrder = randomOrder(c.options.length);
    return { question: c.question, options: applyOrder(c.options, optionOrder), requiredCount: c.requiredCount, optionOrder };
  }
  if (type === 'log_analysis' || type === 'config_table') {
    const c = content as ArtifactPbqContent;
    return {
      scenario: c.scenario,
      artifact: c.artifact,
      subQuestions: c.subQuestions.map(toPublicSubQuestion),
    };
  }
  if (type === 'remediation_select') {
    const c = content as RemediationSelectContent;
    return { scenario: c.scenario, question: c.question, actions: c.actions };
  }
  const c = content as MultipleChoiceContent;
  const optionOrder = randomOrder(c.options.length);
  return { question: c.question, options: applyOrder(c.options, optionOrder), optionOrder };
}
